{% set name = "libpulsar" %}
{% set version = "3.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/apache/pulsar-client-cpp/archive/refs/tags/v{{ version }}.tar.gz
  sha256: be97723dbba43045506f877cbc7600d2efe74264eace980933ae42b387069bc3
  patches:
    - 0001-Link-to-abseil-on-Windows.patch  # [win and (libprotobuf != "3.21")]

build:
  number: 0
  # pulsar doesn't give any ABI guarantees
  run_exports:
    - {{ pin_subpackage('libpulsar', max_pin='x.x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja
    - sed     # [not win]
    - m2-sed  # [win]
    - libprotobuf  # [build_platform != target_platform]
  host:
    - boost-cpp
    - dlfcn-win32  # [win]
    - gmock
    - gtest
    - libcurl
    - libprotobuf
    - openssl
    - snappy
    - zlib
    - zstd

test:
  commands:
    - test -f $PREFIX/lib/libpulsar${SHLIB_EXT}  # [not win]
    - if not exist %LIBRARY_PREFIX%/bin/pulsar.dll exit 1  # [win]
    - if not exist %LIBRARY_PREFIX%/lib/pulsar.lib exit 1  # [win]


about:
  home: https://github.com/apache/pulsar-client-cpp
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Apache Pulsar C++ client library
  dev_url: https://github.com/apache/pulsar-client-cpp
  doc_url: https://pulsar.apache.org/docs/3.0.x/client-libraries

extra:
  recipe-maintainers:
    - xhochy
